name: Linting Checks, Formatting Checks, Tests

on: [pull_request]

permissions:
  contents: read

jobs:
  linting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v12

      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v6

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run Makefile target
        run: make check

  formatting-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  busted-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Busted
        uses: lunarmodules/busted@v2.3.0
        with:
          args: --helper=spec/spec_helper.lua
